describe('Redirect to home', () => {
    it('passes', () => {
    cy.visit('http://localhost:3000/account')
      cy.contains('Sign Out').click()
      cy.url().should('include', '/')
      cy.visit('http://localhost:3000/account')
      cy.contains('Overview').click()
      cy.url().should('include', '/')
      cy.visit('http://localhost:3000/account')
      cy.contains('Settings').click()
      cy.url().should('include', '/')
      cy.visit('http://localhost:3000/account')
      cy.contains('Messages').click()
      cy.url().should('include', '/')
      cy.visit('http://localhost:3000/account')
      cy.contains('My Items').click()
      cy.url().should('include', '/')
      cy.visit('http://localhost:3000/account')
      cy.contains('Achievements').click()
      cy.url().should('include', '/')
    })
})